# Generated by Django 3.2.3 on 2021-05-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostPopularWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField()),
                ('description', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='scrapperresult',
            name='description_result',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapperresult',
            name='title_result',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
