# Generated by Django 3.2.3 on 2021-05-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_auto_20210527_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MostPopularWord',
        ),
        migrations.AddField(
            model_name='scrapperresult',
            name='number_of_search',
            field=models.CharField(default='dupa', max_length=255),
            preserve_default=False,
        ),
    ]
