# Generated by Django 3.2.3 on 2021-05-27 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0003_auto_20210527_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapperresult',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrapperresult',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.0'),
            preserve_default=False,
        ),
    ]
