# Generated by Django 3.2.3 on 2021-05-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0004_auto_20210527_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapperresult',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
