# Generated by Django 3.2.3 on 2021-05-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0005_alter_scrapperresult_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(help_text='in minutes')),
            ],
        ),
    ]
