# Generated by Django 3.2.3 on 2021-05-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0007_auto_20210528_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('scrapper_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google.scrapperresult')),
            ],
        ),
    ]
