# Generated by Django 3.2.3 on 2021-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0009_alter_link_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScrapperResult',
            new_name='SearchResult',
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
